language: go
install: make test
go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5

install:
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - mkdir -p $HOME/gopath/src/gopkg.in
  - mv $HOME/gopath/src/github.com/bsm/openrtb $HOME/gopath/src/bsm/openrtb.v2
  - cd $HOME/gopath/src/bsm/openrtb.v2
